version: '3'
services:
  web:
    image: node:11-alpine
    working_dir: /usr/src/app
    command: yarn start
    environment:
      PUBLIC_URL: http://0.0.0.0:3000/
      NODE_ENV: development
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
